import { APP_URL } from "./static";

export const PUBLIC_ROUTES: string[] = [
  APP_URL.LINKS.HOME,
  APP_URL.LINKS.LOGIN,
  APP_URL.LINKS.REGISTER,
  APP_URL.LINKS.FORGOT_PASSWORD,
  APP_URL.LINKS.OTP_VERIFICATION,
  APP_URL.LINKS.RESET_PASSWORD,
];
